name: Release New Version

run-name: Running tests and checks for policies

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  gooci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: |
          go install github.com/compliance-framework/gooci@latest
          gooci help
