name: Release New Version

run-name: Running tests and checks for policies

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  gooci-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GOOCI cli
        run: go install github.com/compliance-framework/gooci@latest
      - name: GOOCI Login
        run: gooci login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: GOOCI Upload
        run: gooci upload dist/ ghcr.io/compliance-framework/plugin/local-ssh:0.0.5-gh-action
