name: Release New Version

run-name: Running tests and checks for policies

on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/build-and-upload.yml
