name: Build and Release Binaries

run-name: Running tests and checks for policies

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GOOCI cli
        run: go install github.com/compliance-framework/gooci@latest
      - name: GOOCI Upload
        run: gooci upload dist/ ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{github.ref_name}}
